dim: 2
type: float
is_exact: 0
is_sparse_lu: true

space:
  x: [0.0,2.0]
  y: [0.0,1.0]

time: [0.0, 0.5]

condition:
  bound_value:
    x: [0.0, 0.0]
    y: [0.0, 0.0]

  initial_value:
    t: 1.0

delta:
  t: 0.001
  x: 0.02
  y: 0.02

solver:
    - type    : imp
      boundary:
        x: [0.0, 2.0]
        y: [0.0, 1.0]
      coef: 1.0
      t_delta: -1.0
