dim: 2
type: float
is_exact: 0
is_sparse_lu: true
try_time: 1

space:
  x: [0.0,1.0]
  y: [0.0,1.0]

time: [0.0, 20]

condition:
  bound_value:
    x: [0.0, 0.0]
    y: [0.0, 0.0]

  initial_value:
    t: 1.0

delta:
  t: 8e-6
  x: 0.02
  y: 0.02

solver:
    - type    : exp
      boundary:
        x: [0.0, 0.3]
        y: [0.0, 1.0]
      coef: 0.01
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [0.3, 0.4]
        y: [0.0, 1.0]
      coef: 10
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [0.4, 0.7]
        y: [0.0, 1.0]
      coef: 0.01
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [0.7, 0.8]
        y: [0.0, 1.0]
      coef: 10
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [0.8, 1.0]
        y: [0.0, 1.0]
      coef: 0.01
      t_delta: -1.0
