dim: 2
type: float
is_exact: 0
is_sparse_lu: true
try_time: 100

space:
  x: [0.0, 36000]
  y: [0.0, 24000]

time: [0.0, 120]

condition:
  bound_value:
    x: [0.0, 0.0]
    y: [0.0, 0.0]

  initial_value:
    t: 20

delta:
  t: 0.0045 # max 0.004629
  x: 300
  y: 400

solver:
    - type    : exp
      boundary:
        x: [0.0, 7500]
        y: [0.0, 24000]
      coef: 6220800.0
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [7500, 9000]
        y: [0.0, 24000]
      coef: 5.39
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [9000, 16500]
        y: [0.0, 24000]
      coef: 6220800.0
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [16500, 18000]
        y: [0.0, 24000]
      coef: 5.39
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [18000, 25500]
        y: [0.0, 24000]
      coef: 6220800.0
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [25500, 27000]
        y: [0.0, 24000]
      coef: 5.39
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [27000, 36000]
        y: [0.0, 24000]
      coef: 6220800.0
      t_delta: -1.0