dim: 1
type: float
is_exact: 0
try_time: 100
space:
  x: [0.0,1.0]

time: [0.0, 2.5]

condition:
  bound_value:
    x: [0.0, 0.0]

  initial_value:
    t: 10.0

delta:
  t: 0.04
  x: 0.1

solver:
    - type    : imp
      boundary:
        x: [0.0, 0.4]
      coef: 10.0
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [0.4, 1.0]
      coef: 0.1
      t_delta: -1.0
