dim: 2
type: float
is_exact: 0
is_sparse_lu: true
try_time: 1

space:
  x: [0.0, 36000]
  y: [0.0, 24000]

time: [0.0, 24000]

condition:
  bound_value:
    x: [0.0, 0.0]
    y: [0.0, 0.0]

  initial_value:
    t: 20

delta:
  t: 12 # max 0.35
  x: 300
  y: 400

solver:
    - type    : exp
      boundary:
        x: [0.0, 7500]
        y: [0.0, 24000]
      coef: 5.39
      t_delta: -1.0
    - type    : imp
      boundary:
        x: [7500, 9600]
        y: [0.0, 24000]
      coef: 622080.0
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [9600, 16200]
        y: [0.0, 24000]
      coef: 5.39
      t_delta: -1.0
    - type    : imp
      boundary:
        x: [16200, 18300]
        y: [0.0, 24000]
      coef: 622080.0
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [18300, 25500]
        y: [0.0, 24000]
      coef: 5.39
      t_delta: -1.0
    - type    : imp
      boundary:
        x: [25500, 28200]
        y: [0.0, 24000]
      coef: 622080.0
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [28200, 36000]
        y: [0.0, 24000]
      coef: 5.39
      t_delta: -1.0