dim: 1
type: float
is_exact: 1
try_time: 1
space:
  x: [0.0,1.0]

time: [0.0, 0.5]

condition:
  bound_value:
    x: [0.0, 0.0]

  initial_value:
    t: 1.0

delta:
  t: 0.004
  x: 0.01

solver:
    - type    : imp
      boundary:
        x: [0.0, 1.0]
      coef: 0.01
      t_delta: -1.0
    - type    : exp
      boundary:
        x: [1.0, 1.0]
      coef: 0.01
      t_delta: -1.0
